/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every loaded flow.
         * @description Sorted alphabetically by name.
         */
        get: operations["listFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the full source YAML for one flow.
         * @description The `{path}` parameter is greedy and matches slashes.
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live flow activity stream.
         * @description Server-Sent Events with two named event types:
         *     `snapshot` (an object keyed by flow identity containing the
         *     current metrics for every known flow, sent once on connect) and
         *     `log` (one `LogRecord` per frame — the same shape as
         *     `/api/logs/stream`). The client filters the log stream down to
         *     task-scoped records for its per-flow activity panels; the raw
         *     stream is emitted so both `/logs` and per-flow views share the
         *     same wire format.
         */
        get: operations["streamFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every resource discoverable by the resource loader. */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one resource's raw text content.
         * @description The `{key}` path parameter is greedy and matches slashes.
         */
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global log record snapshot.
         * @description Returns every log record retained by the telemetry backend,
         *     including framework, lifecycle, and per-task activity records.
         *     The per-flow activity feed (`/api/flows/stream`) is a scoped
         *     subset of the same source; this endpoint returns the full set.
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live global log stream.
         * @description Server-Sent Events with a single named event type `log` carrying
         *     one `LogRecord` per frame. Emits every captured record; the
         *     admin UI applies level, task, flow, and free-text filters
         *     client-side.
         */
        get: operations["streamLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the running flowgen build version. */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the running application configuration.
         * @description The loaded `AppConfig` serialized to YAML, read-only. Secret
         *     values (JWT HMAC keys) are redacted to `"***"` before
         *     serialization; file paths, URLs, ports, and other non-secret
         *     settings are shown verbatim.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes liveness probe.
         * @description Always returns 200 while the health listener is running.
         */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes readiness probe.
         * @description Returns 200 once at least one flow is registered, 503 before.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias of `/livez`. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Registry entry combined with tracing-derived counters. */
        FlowSummary: {
            /**
             * @description Identity of the flow. Filesystem-loaded flows use the path
             *     relative to `flows.path` with the extension stripped
             *     (e.g. `demo/nba_email_demo`); cache-loaded flows use the
             *     KV key suffix after `flowgen.flows.`. Root-level flows
             *     have no `/`.
             */
            path: string;
            /**
             * @description Flow name as declared in the YAML `flow.name` field. Not
             *     guaranteed to be globally unique — use `path` for identity.
             */
            name: string;
            /**
             * @description Human-readable name taken from `labels.display_name`. UI
             *     falls back to `name` when absent.
             */
            display_name: string | null;
            /** @description Optional description taken from the `description` label. */
            description: string | null;
            /** @description Tags taken from the `tags` label array (empty when none). */
            tags: string[];
            /** @description Whether the flow requires distributed leader election. */
            require_leader_election: boolean;
            /** @description Number of tasks in the flow. */
            task_count: number;
            /**
             * @description Where the config was loaded from.
             * @enum {string}
             */
            source: "filesystem" | "cache";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of when the flow supervisor was spawned.
             */
            started_at: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of the most recent `info!` inside a
             *     `task.handle` scope. Null when the flow has never
             *     processed an event.
             */
            last_event_at: string | null;
            /** Format: date-time */
            last_warning_at: string | null;
            /** Format: date-time */
            last_error_at: string | null;
            /** Format: int64 */
            events_total: number;
            /** Format: int64 */
            warnings_total: number;
            /** Format: int64 */
            errors_total: number;
            status: components["schemas"]["FlowStatus"];
        };
        /**
         * @description Coarse status derived from the last-seen info / warn / error
         *     timestamps. Wins by recency — an error after an info stays
         *     `error` until the next info arrives.
         * @enum {string}
         */
        FlowStatus: "idle" | "ok" | "warn" | "error";
        FlowDetail: {
            /** @description Identity of the flow; see `FlowSummary.path`. */
            path: string;
            name: string;
            display_name: string | null;
            /** @description Raw YAML source of the flow config. */
            yaml: string;
        };
        ResourceSummary: {
            /** @description Resource key relative to the loader's base path. */
            key: string;
            /** @description Filename extension — used by the UI to pick a viewer. */
            extension: string | null;
            /**
             * Format: int64
             * @description File size in bytes; null for cache-backed entries.
             */
            size: number | null;
        };
        ResourceContent: {
            key: string;
            extension: string | null;
            /** @description UTF-8 file contents. */
            content: string;
        };
        VersionInfo: {
            /** @description SemVer version derived from `CARGO_PKG_VERSION`. */
            version: string;
        };
        ConfigInfo: {
            /**
             * @description The running `AppConfig` serialized to YAML, with secrets
             *     redacted to `"***"`.
             */
            yaml: string;
        };
        /** @description One span in a log record's span chain, root-to-leaf. */
        LogSpan: {
            /** @description Span name (e.g. `flow.run`, `task.run`, `task.handle`). */
            name: string;
            /** @description Fields declared on this span, flattened to strings. */
            fields: components["schemas"]["KeyValue"][];
        };
        /** @description Ordered key/value pair. Kept as an array of these instead of a map so duplicate keys are preserved. */
        KeyValue: {
            key: string;
            value: string;
        };
        /**
         * @description A single log line captured by the telemetry backend, wire-shape
         *     of the internal `StoredLog`. Framework consumers get span
         *     topology (`spans`) alongside event-level `fields` so they can
         *     classify records without parsing a flat attribute bag.
         */
        LogRecord: {
            /** @description The tracing event's `message` field. */
            body: string;
            /**
             * @description Lowercased tracing level.
             * @enum {string}
             */
            level: "info" | "warn" | "error" | "debug" | "trace";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when present in the source line.
             */
            timestamp?: string | null;
            /** @description The tracing `target` (usually the module path). */
            target: string;
            /** @description Span chain from root to leaf. Empty for events emitted outside any span. */
            spans: components["schemas"]["LogSpan"][];
            /** @description Fields declared on the event itself (not inherited from spans). */
            fields: components["schemas"]["KeyValue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per loaded flow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSummary"][];
                };
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow identity (see `FlowSummary.path`). */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow detail including raw YAML source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            /** @description No flow with that name is loaded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    streamFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per resource (filesystem + cache combined). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"][];
                };
            };
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource key relative to the loader's base path. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full text content of the resource. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceContent"];
                };
            };
            /** @description Resource not found in filesystem or cache. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listLogs: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (most recent first). */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retained framework logs, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRecord"][];
                };
            };
        };
    };
    streamLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build version derived from `CARGO_PKG_VERSION`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted application configuration as YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigInfo"];
                };
            };
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not ready — no flows registered yet. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
