/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every loaded flow.
         * @description Sorted alphabetically by name.
         */
        get: operations["listFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the full source YAML for one flow.
         * @description The `{path}` parameter is greedy and matches slashes.
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live flow metrics stream.
         * @description Server-Sent Events with a single named event type `snapshot` (an
         *     object keyed by flow identity containing the current metrics for
         *     every known flow), sent once on connect and again whenever any
         *     flow's counters change. Event/log history and live tail for a
         *     flow come from `/api/logs` and `/api/logs/stream` (with `flow`
         *     set) — the same source the global `/logs` viewer uses — not from
         *     this endpoint.
         */
        get: operations["streamFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every resource discoverable by the resource loader. */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one resource's raw text content.
         * @description The `{key}` path parameter is greedy and matches slashes.
         */
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log record snapshot, optionally scoped to one flow.
         * @description Returns log records retained by the telemetry backend, including
         *     framework, lifecycle, and per-task activity records. The per-flow
         *     Activity panel calls this with `flow` set to backfill its history
         *     from the same source the global `/logs` viewer uses (unscoped).
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live log stream, optionally scoped to one flow.
         * @description Server-Sent Events with a single named event type `log` carrying
         *     one `LogRecord` per frame. Unscoped, this emits every captured
         *     record and the admin UI applies level and free-text filters
         *     client-side; the per-flow Activity panel passes `flow` so it only
         *     receives that flow's live records.
         */
        get: operations["streamLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the running flowgen build version. */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the running application configuration.
         * @description The loaded `AppConfig` serialized to YAML, read-only. Secret
         *     values (JWT HMAC keys) are redacted to `"***"` before
         *     serialization; file paths, URLs, ports, and other non-secret
         *     settings are shown verbatim.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy a chat completion to the AI gateway.
         * @description Forwards an OpenAI-compatible chat completion request to the
         *     configured AI gateway (`web.ai_gateway_url`, or the same-process
         *     gateway on loopback) and streams the response back. Same-origin
         *     with the admin server, so the built-in Agents chat needs no
         *     gateway-side CORS. The request and response bodies are the stock
         *     OpenAI chat-completions shape; route by `model`
         *     (`"<gateway-name>/<downstream-model>"`).
         */
        post: operations["agentsChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List models available on the AI gateway.
         * @description Proxies the AI gateway model list so the Agents chat can populate
         *     its model selector without knowing the gateway URL. Returns the
         *     stock OpenAI `{ object: "list", data: [{ id, ... }] }` shape.
         */
        get: operations["agentsModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored Agents chat conversations.
         * @description Returns conversation summaries (no message bodies) for the built-in
         *     Agents chat, newest first. History is our UI's own store in the
         *     configured system cache — the gateway proxy stays stateless. A
         *     persistence flow can copy these into a database for long-term
         *     retention.
         */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one conversation with its full message history. */
        get: operations["getConversation"];
        /**
         * Create or overwrite a conversation.
         * @description The path id is authoritative and `updatedAt` is server-stamped, so
         *     neither is read from the body. The TTL
         *     (`web.agents.conversation_history_ttl`) is refreshed on every write,
         *     so the expiry window counts from the last activity.
         */
        put: operations["putConversation"];
        post?: never;
        /**
         * Delete a conversation.
         * @description Idempotent — deleting a missing id still succeeds.
         */
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Starts admin UI login.
         * @description Redirects to the configured OIDC identity provider. 404 when
         *     `web.auth` is not configured.
         */
        get: operations["authLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC redirect target.
         * @description Exchanges the authorization code for tokens, verifies state/nonce,
         *     and sets the session cookie. Not meant to be called directly —
         *     the identity provider redirects here after `/auth/login`.
         */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clears the local session cookie. */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user.
         * @description 404 when `web.auth` is not configured — distinct from 401 (not
         *     signed in) so callers can tell "no login offered" apart from
         *     "not logged in yet".
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes liveness probe.
         * @description Always returns 200 while the health listener is running.
         */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes readiness probe.
         * @description Returns 200 once at least one flow is registered, 503 before.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias of `/livez`. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Registry entry combined with tracing-derived counters. */
        FlowSummary: {
            /**
             * @description Identity of the flow. Filesystem-loaded flows use the path
             *     relative to `flows.path` with the extension stripped
             *     (e.g. `demo/nba_email_demo`); cache-loaded flows use the
             *     KV key suffix after `flowgen.flows.`. Root-level flows
             *     have no `/`.
             */
            path: string;
            /**
             * @description Flow name as declared in the YAML `flow.name` field. Not
             *     guaranteed to be globally unique — use `path` for identity.
             */
            name: string;
            /**
             * @description Human-readable name taken from `labels.display_name`. UI
             *     falls back to `name` when absent.
             */
            display_name: string | null;
            /** @description Optional description taken from the `description` label. */
            description: string | null;
            /** @description Tags taken from the `tags` label array (empty when none). */
            tags: string[];
            /** @description Whether the flow requires distributed leader election. */
            require_leader_election: boolean;
            /** @description Number of tasks in the flow. */
            task_count: number;
            /**
             * @description Where the config was loaded from.
             * @enum {string}
             */
            source: "filesystem" | "cache";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of when the flow supervisor was spawned.
             */
            started_at: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of the most recent `info!` inside a
             *     `task.handle` scope. Null when the flow has never
             *     processed an event.
             */
            last_event_at: string | null;
            /** Format: date-time */
            last_warning_at: string | null;
            /** Format: date-time */
            last_error_at: string | null;
            /** Format: int64 */
            events_total: number;
            /** Format: int64 */
            warnings_total: number;
            /** Format: int64 */
            errors_total: number;
            status: components["schemas"]["FlowStatus"];
        };
        /**
         * @description Coarse status derived from the last-seen info / warn / error
         *     timestamps. Wins by recency — an error after an info stays
         *     `error` until the next info arrives.
         * @enum {string}
         */
        FlowStatus: "idle" | "ok" | "warn" | "error";
        FlowDetail: {
            /** @description Identity of the flow; see `FlowSummary.path`. */
            path: string;
            name: string;
            display_name: string | null;
            /** @description Raw YAML source of the flow config. */
            yaml: string;
        };
        ResourceSummary: {
            /** @description Resource key relative to the loader's base path. */
            key: string;
            /** @description Filename extension — used by the UI to pick a viewer. */
            extension: string | null;
            /**
             * Format: int64
             * @description File size in bytes; null for cache-backed entries.
             */
            size: number | null;
        };
        ResourceContent: {
            key: string;
            extension: string | null;
            /** @description UTF-8 file contents. */
            content: string;
        };
        VersionInfo: {
            /** @description SemVer version derived from `CARGO_PKG_VERSION`. */
            version: string;
        };
        ConfigInfo: {
            /**
             * @description The running `AppConfig` serialized to YAML, with secrets
             *     redacted to `"***"`.
             */
            yaml: string;
        };
        /** @description A resolved identity from the configured OIDC provider. */
        UserContext: {
            /** @description Extracted from the `sub` claim (or `web.auth`'s configured claim). */
            user_id: string;
            /** @description All claims from the ID token. */
            claims: {
                [key: string]: unknown;
            };
        };
        /** @description One tool call an agent made while producing a message. */
        ToolStep: {
            /** @description The tool's name. */
            name: string;
            /** @description The tool call's arguments, as a JSON string. */
            arguments: string;
        };
        /** @description One message in an Agents chat conversation. */
        ConversationMessage: {
            /** @description Message author — `user` or `assistant`. */
            role: string;
            /** @description The message text. */
            content: string;
            /**
             * Format: int64
             * @description When the message was sent, epoch milliseconds.
             */
            at: number;
            /** @description Tool calls the agent ran while producing this message, in order. */
            steps?: components["schemas"]["ToolStep"][];
        };
        /** @description A stored Agents chat conversation with its full history. */
        Conversation: {
            /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
            id: string;
            /** @description Human-readable conversation title. */
            title: string;
            messages: components["schemas"]["ConversationMessage"][];
            /** @description The gateway model id last used for this conversation. */
            model?: string;
            /**
             * Format: int64
             * @description Last write time, epoch milliseconds (server-stamped).
             */
            updatedAt: number;
        };
        /** @description A conversation without its messages, for the list view. */
        ConversationSummary: {
            id: string;
            title: string;
            /**
             * Format: int64
             * @description Last write time, epoch milliseconds.
             */
            updatedAt: number;
            /** @description Number of messages in the conversation. */
            messageCount: number;
        };
        /**
         * @description Body for `PUT /api/agents/conversations/{id}`. `id` and `updatedAt`
         *     are set by the server (path is authoritative, timestamp is
         *     server-stamped), so they are not part of this body.
         */
        ConversationUpsert: {
            title: string;
            messages: components["schemas"]["ConversationMessage"][];
            /** @description The gateway model id last used for this conversation. */
            model?: string;
        };
        /** @description One span in a log record's span chain, root-to-leaf. */
        LogSpan: {
            /** @description Span name (e.g. `flow.run`, `task.run`, `task.handle`). */
            name: string;
            /** @description Fields declared on this span, flattened to strings. */
            fields: components["schemas"]["KeyValue"][];
        };
        /** @description Ordered key/value pair. Kept as an array of these instead of a map so duplicate keys are preserved. */
        KeyValue: {
            key: string;
            value: string;
        };
        /**
         * @description A single log line captured by the telemetry backend, wire-shape
         *     of the internal `StoredLog`. Framework consumers get span
         *     topology (`spans`) alongside event-level `fields` so they can
         *     classify records without parsing a flat attribute bag.
         */
        LogRecord: {
            /** @description The tracing event's `message` field. */
            body: string;
            /**
             * @description Lowercased tracing level.
             * @enum {string}
             */
            level: "info" | "warn" | "error" | "debug" | "trace";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when present in the source line.
             */
            timestamp?: string | null;
            /** @description The tracing `target` (usually the module path). */
            target: string;
            /** @description Span chain from root to leaf. Empty for events emitted outside any span. */
            spans: components["schemas"]["LogSpan"][];
            /** @description Fields declared on the event itself (not inherited from spans). */
            fields: components["schemas"]["KeyValue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per loaded flow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSummary"][];
                };
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow identity (see `FlowSummary.path`). */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow detail including raw YAML source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            /** @description No flow with that name is loaded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    streamFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per resource (filesystem + cache combined). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"][];
                };
            };
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource key relative to the loader's base path. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full text content of the resource. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceContent"];
                };
            };
            /** @description Resource not found in filesystem or cache. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listLogs: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (most recent first). */
                limit?: number;
                /** @description Restrict to one flow's records, by flow identity. */
                flow?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retained framework logs, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRecord"][];
                };
            };
        };
    };
    streamLogs: {
        parameters: {
            query?: {
                /** @description Restrict to one flow's records, by flow identity. */
                flow?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build version derived from `CARGO_PKG_VERSION`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted application configuration as YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigInfo"];
                };
            };
        };
    };
    agentsChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OpenAI-compatible completion, streamed when `stream` is true. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The AI gateway could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No AI gateway is configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentsModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAI-compatible model list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The AI gateway could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No AI gateway is configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation summaries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversations: components["schemas"]["ConversationSummary"][];
                    };
                };
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No conversation with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpsert"];
            };
        };
        responses: {
            /** @description The conversation was stored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the identity provider. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login succeeded; redirects back into the admin UI. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid code or state, or the provider reported an error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Code exchange or ID token validation failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserContext"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not ready — no flows registered yet. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
