/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/flows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List every loaded flow.
         * @description Sorted alphabetically by name.
         */
        get: operations["listFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the full source YAML for one flow.
         * @description The `{path}` parameter is greedy and matches slashes.
         */
        get: operations["getFlow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/flows/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live flow metrics stream.
         * @description Server-Sent Events with a single named event type `snapshot` (an
         *     object keyed by flow identity containing the current metrics for
         *     every known flow), sent once on connect and again whenever any
         *     flow's counters change. Event/log history and live tail for a
         *     flow come from `/api/logs` and `/api/logs/stream` (with `flow`
         *     set) — the same source the global `/logs` viewer uses — not from
         *     this endpoint.
         */
        get: operations["streamFlows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every resource discoverable by the resource loader. */
        get: operations["listResources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resources/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch one resource's raw text content.
         * @description The `{key}` path parameter is greedy and matches slashes.
         */
        get: operations["getResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Log record snapshot, optionally scoped to one flow.
         * @description Returns log records retained by the telemetry backend, including
         *     framework, lifecycle, and per-task activity records. The per-flow
         *     Activity panel calls this with `flow` set to backfill its history
         *     from the same source the global `/logs` viewer uses (unscoped).
         */
        get: operations["listLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live log stream, optionally scoped to one flow.
         * @description Server-Sent Events with a single named event type `log` carrying
         *     one `LogRecord` per frame. Unscoped, this emits every captured
         *     record; the web UI passes `levels` and applies free-text filters
         *     client-side, and the per-flow Activity panel passes `flow` so it
         *     only receives that flow's live records.
         */
        get: operations["streamLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cluster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every pod behind the web UI, with reachability and flow count.
         * @description With the `memory` telemetry backend and the cache, the serving pod
         *     checks every registered pod; logs and flow counters of an
         *     unreachable pod are missing from `/api/logs`, `/api/flows`, and
         *     their streams. Otherwise only the serving pod is listed.
         */
        get: operations["getClusterStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cluster/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replace the token pods use to reach each other.
         * @description Available in cluster mode: the `memory` telemetry backend with the
         *     cache. Generates a new
         *     random token in the system cache, e.g. after the current one
         *     leaked. Every pod switches to it within 30 seconds; until then,
         *     some pods may miss others' logs and counters.
         */
        post: operations["regenerateClusterToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the running flowgen build version. */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the running application configuration.
         * @description The loaded `AppConfig` serialized to YAML, read-only. Secret
         *     values (JWT HMAC keys) are redacted to `"***"` before
         *     serialization; file paths, URLs, ports, and other non-secret
         *     settings are shown verbatim.
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy a chat completion to the AI gateway.
         * @description Forwards an OpenAI-compatible chat completion request to the
         *     configured AI gateway (`web.ai_gateway_url`, or the same-process
         *     gateway on loopback) and streams the response back. Same-origin
         *     with the web server, so the built-in Agents chat needs no
         *     gateway-side CORS. The request and response bodies are the stock
         *     OpenAI chat-completions shape; route by `model`
         *     (`"<gateway-name>/<downstream-model>"`).
         */
        post: operations["agentsChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List models available on the AI gateway.
         * @description Proxies the AI gateway model list so the Agents chat can populate
         *     its model selector without knowing the gateway URL. Returns the
         *     stock OpenAI `{ object: "list", data: [{ id, ... }] }` shape.
         */
        get: operations["agentsModels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored Agents chat conversations.
         * @description Returns conversation summaries (no message bodies) for the built-in
         *     Agents chat, newest first. History is our UI's own store in the
         *     configured system cache — the gateway proxy stays stateless. A
         *     persistence flow can copy these into a database for long-term
         *     retention.
         */
        get: operations["listConversations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one conversation with its full message history. */
        get: operations["getConversation"];
        /**
         * Create or overwrite a conversation.
         * @description The path id is authoritative and `updatedAt` is server-stamped, so
         *     neither is read from the body. The TTL
         *     (`web.agents.conversation_history_ttl`) is refreshed on every write,
         *     so the expiry window counts from the last activity.
         */
        put: operations["putConversation"];
        post?: never;
        /**
         * Delete a conversation.
         * @description Idempotent — deleting a missing id still succeeds.
         */
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate flow and resource files without running them.
         * @description Paths are relative to the workspace root: `flows/…` files are parsed
         *     and checked as flows (unknown fields, task wiring, task settings,
         *     inline scripts), `resources/…` files by extension (`.rhai` must
         *     compile, `.json` must parse).
         */
        post: operations["validateWorkspaceFiles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List proposed workspace changes, newest first. */
        get: operations["listChanges"];
        put?: never;
        /**
         * Propose a workspace change for approval.
         * @description Records the change as pending together with the deployed content of
         *     every file it touches, so the diff shows exactly what approval
         *     replaces. Invalid files are recorded too, with their issues.
         */
        post: operations["proposeChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Fetch one change with its diff. */
        get: operations["getChange"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a pending change and publish it, or publish a failed one again.
         * @description Requires a signed-in user's session, and membership of one of
         *     `web.authoring.approver_groups` when set; machine keys are refused.
         *     Runs the flow behind `web.authoring.publish_endpoint` with
         *     `{id, title, author, files}` and records its result. A `failed`
         *     change, or one left `publishing` past `web.authoring.publish_timeout`,
         *     can be approved again.
         */
        post: operations["approveChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/changes/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a pending or failed change. */
        post: operations["rejectChange"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Starts web UI login.
         * @description Redirects to the configured OIDC identity provider. 404 when
         *     `web.auth` is not configured.
         */
        get: operations["authLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * OIDC redirect target.
         * @description Exchanges the authorization code for tokens, verifies state/nonce,
         *     and sets the session cookie. Not meant to be called directly —
         *     the identity provider redirects here after `/auth/login`.
         */
        get: operations["authCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clears the local session cookie and redirects.
         * @description Navigated to, not fetched — the browser follows the redirect chain
         *     itself. Redirects to `web.auth.signout_redirect_url` when set (with
         *     `id_token_hint` appended), ending the identity provider's session as
         *     well; otherwise back to the web UI, having cleared flowgen's session
         *     only.
         */
        get: operations["authLogout"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The signed-in user.
         * @description Validates the session, silently refreshing it against the identity
         *     provider once past `exp` — the same check `/api/*` applies, so a
         *     caller that gets 200 here will not be rejected a moment later.
         *
         *     404 when `web.auth` is not configured — distinct from 401 (not
         *     signed in) so callers can tell "no login offered" apart from
         *     "not logged in yet".
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/livez": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes liveness probe.
         * @description Always returns 200 while the health listener is running.
         */
        get: operations["livez"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Kubernetes readiness probe.
         * @description Returns 200 once at least one flow is registered, 503 before.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alias of `/livez`. */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Registry entry combined with tracing-derived counters. */
        FlowSummary: {
            /**
             * @description Identity of the flow. Filesystem-loaded flows use the path
             *     relative to `flows.path` with the extension stripped
             *     (e.g. `demo/nba_email_demo`); cache-loaded flows use the
             *     KV key suffix after `flowgen.flows.`. Root-level flows
             *     have no `/`.
             */
            path: string;
            /**
             * @description Flow name as declared in the YAML `flow.name` field. Not
             *     guaranteed to be globally unique — use `path` for identity.
             */
            name: string;
            /**
             * @description Human-readable name taken from `labels.display_name`. UI
             *     falls back to `name` when absent.
             */
            display_name: string | null;
            /** @description Optional description taken from the `description` label. */
            description: string | null;
            /** @description Tags taken from the `tags` label array (empty when none). */
            tags: string[];
            /** @description Whether the flow requires distributed leader election. */
            require_leader_election: boolean;
            /** @description Number of tasks in the flow. */
            task_count: number;
            /**
             * @description Where the config was loaded from.
             * @enum {string}
             */
            source: "filesystem" | "cache";
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of when the flow supervisor was spawned.
             */
            started_at: string | null;
            /**
             * Format: date-time
             * @description RFC 3339 timestamp of the most recent `info!` inside a
             *     `task.handle` scope. Null when the flow has never
             *     processed an event.
             */
            last_event_at: string | null;
            /** Format: date-time */
            last_warning_at: string | null;
            /** Format: date-time */
            last_error_at: string | null;
            /** Format: int64 */
            events_total: number;
            /** Format: int64 */
            warnings_total: number;
            /** Format: int64 */
            errors_total: number;
            status: components["schemas"]["FlowStatus"];
        };
        /**
         * @description Coarse status derived from the last-seen info / warn / error
         *     timestamps. Wins by recency — an error after an info stays
         *     `error` until the next info arrives.
         * @enum {string}
         */
        FlowStatus: "idle" | "ok" | "warn" | "error";
        FlowDetail: {
            /** @description Identity of the flow; see `FlowSummary.path`. */
            path: string;
            name: string;
            display_name: string | null;
            /** @description Raw YAML source of the flow config. */
            yaml: string;
        };
        ResourceSummary: {
            /** @description Resource key relative to the loader's base path. */
            key: string;
            /** @description Filename extension — used by the UI to pick a viewer. */
            extension: string | null;
            /**
             * Format: int64
             * @description File size in bytes; null for cache-backed entries.
             */
            size: number | null;
        };
        ResourceContent: {
            key: string;
            extension: string | null;
            /** @description UTF-8 file contents. */
            content: string;
        };
        ClusterStatus: {
            /** @description Registered pods, the serving pod included, sorted by identity. */
            pods: components["schemas"]["PodStatus"][];
        };
        PodStatus: {
            /** @description Pod identity. */
            identity: string;
            /** @description `host:port` the pod advertises for the cluster endpoint. */
            address?: string;
            /** @description Why its logs and counters are missing from merged views. Absent when present. */
            unreachable_reason?: string;
            /** @description Flows running on the pod. Absent when it is unreachable. */
            flows?: number;
        };
        VersionInfo: {
            /** @description SemVer version derived from `CARGO_PKG_VERSION`. */
            version: string;
        };
        ConfigInfo: {
            /**
             * @description The running `AppConfig` serialized to YAML, with secrets
             *     redacted to `"***"`.
             */
            yaml: string;
            /** @description Whether `web.authoring` is set, so changes can be proposed. */
            authoring: boolean;
        };
        /** @description A resolved identity from the configured OIDC provider. */
        UserContext: {
            /** @description Extracted from the `sub` claim (or `web.auth`'s configured claim). */
            user_id: string;
            /** @description All claims from the ID token. */
            claims: {
                [key: string]: unknown;
            };
        };
        /** @description One tool call an agent made while producing a message. */
        ToolStep: {
            /** @description The tool's name. */
            name: string;
            /** @description The tool call's arguments, as a JSON string. */
            arguments: string;
        };
        /** @description A file in the workspace; `content` null deletes it. */
        WorkspaceFile: {
            /** @description Path from the workspace root, under `flows/` or `resources/`. */
            path: string;
            content?: string | null;
        };
        WorkspaceFiles: {
            files: components["schemas"]["WorkspaceFile"][];
        };
        ValidationIssue: {
            /** @description The file the issue is in. */
            path: string;
            /** @description Where in the file, e.g. `flow.tasks.0.generate.intreval`. */
            location?: string;
            message: string;
        };
        WorkspaceValidation: {
            issues: components["schemas"]["ValidationIssue"][];
        };
        ChangeProposal: {
            /** @description One line, used as the commit message. */
            title: string;
            description?: string;
            files: components["schemas"]["WorkspaceFile"][];
        };
        /** @enum {string} */
        ChangeStatus: "pending" | "rejected" | "publishing" | "published" | "failed";
        ChangeFile: {
            path: string;
            /** @description Proposed content; null deletes the file. */
            content?: string | null;
            /** @description Deployed content when the change was proposed; null for a new file. */
            previous?: string | null;
            /** @description Unified diff from `previous` to `content`. */
            diff: string;
        };
        Change: {
            id: string;
            title: string;
            description?: string;
            status: components["schemas"]["ChangeStatus"];
            /** @description The user or machine key that proposed the change. */
            proposedBy: string;
            /**
             * Format: int64
             * @description Epoch milliseconds.
             */
            createdAt: number;
            /** @description The user who approved or rejected the change. */
            decidedBy?: string;
            /** Format: int64 */
            decidedAt?: number;
            files: components["schemas"]["ChangeFile"][];
            issues: components["schemas"]["ValidationIssue"][];
            /** @description What the publish flow returned, e.g. the commit and digest. */
            result?: {
                [key: string]: unknown;
            };
            /** @description Why publishing failed. */
            error?: string;
        };
        ChangeSummary: {
            /** @description Workspace paths the change touches. */
            paths: string[];
            id: string;
            title: string;
            status: components["schemas"]["ChangeStatus"];
            proposedBy: string;
            /** Format: int64 */
            createdAt: number;
            fileCount: number;
        };
        /** @description One message in an Agents chat conversation. */
        ConversationMessage: {
            /** @description Message author — `user` or `assistant`. */
            role: string;
            /** @description The message text. */
            content: string;
            /**
             * Format: int64
             * @description When the message was sent, epoch milliseconds.
             */
            at: number;
            /** @description Tool calls the agent ran while producing this message, in order. */
            steps?: components["schemas"]["ToolStep"][];
        };
        /** @description A stored Agents chat conversation with its full history. */
        Conversation: {
            /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
            id: string;
            /** @description Human-readable conversation title. */
            title: string;
            messages: components["schemas"]["ConversationMessage"][];
            /** @description The gateway model id last used for this conversation. */
            model?: string;
            /**
             * Format: int64
             * @description Last write time, epoch milliseconds (server-stamped).
             */
            updatedAt: number;
        };
        /** @description A conversation without its messages, for the list view. */
        ConversationSummary: {
            id: string;
            title: string;
            /**
             * Format: int64
             * @description Last write time, epoch milliseconds.
             */
            updatedAt: number;
            /** @description Number of messages in the conversation. */
            messageCount: number;
        };
        /**
         * @description Body for `PUT /api/agents/conversations/{id}`. `id` and `updatedAt`
         *     are set by the server (path is authoritative, timestamp is
         *     server-stamped), so they are not part of this body.
         */
        ConversationUpsert: {
            title: string;
            messages: components["schemas"]["ConversationMessage"][];
            /** @description The gateway model id last used for this conversation. */
            model?: string;
        };
        /** @description One span in a log record's span chain, root-to-leaf. */
        LogSpan: {
            /** @description Span name (e.g. `flow.run`, `task.run`, `task.handle`). */
            name: string;
            /** @description Fields declared on this span, flattened to strings. */
            fields: components["schemas"]["KeyValue"][];
        };
        /** @description Ordered key/value pair. Kept as an array of these instead of a map so duplicate keys are preserved. */
        KeyValue: {
            key: string;
            value: string;
        };
        /**
         * @description Lowercased tracing level.
         * @enum {string}
         */
        LogLevel: "info" | "warn" | "error" | "debug" | "trace";
        /**
         * @description A single log line captured by the telemetry backend, wire-shape
         *     of the internal `StoredLog`. Framework consumers get span
         *     topology (`spans`) alongside event-level `fields` so they can
         *     classify records without parsing a flat attribute bag.
         */
        LogRecord: {
            /** @description The tracing event's `message` field. */
            body: string;
            level: components["schemas"]["LogLevel"];
            /**
             * Format: date-time
             * @description RFC 3339 timestamp when present in the source line.
             */
            timestamp?: string | null;
            /** @description The tracing `target` (usually the module path). */
            target: string;
            /** @description Span chain from root to leaf. Empty for events emitted outside any span. */
            spans: components["schemas"]["LogSpan"][];
            /** @description Fields declared on the event itself (not inherited from spans). */
            fields: components["schemas"]["KeyValue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per loaded flow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowSummary"][];
                };
            };
        };
    };
    getFlow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow identity (see `FlowSummary.path`). */
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow detail including raw YAML source. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowDetail"];
                };
            };
            /** @description No flow with that name is loaded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    streamFlows: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    listResources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One entry per resource (filesystem + cache combined). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceSummary"][];
                };
            };
        };
    };
    getResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Resource key relative to the loader's base path. */
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full text content of the resource. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceContent"];
                };
            };
            /** @description Resource not found in filesystem or cache. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    listLogs: {
        parameters: {
            query?: {
                /** @description Maximum number of records to return (most recent first). */
                limit?: number;
                /** @description Restrict to one flow's records, by flow identity. */
                flow?: string;
                /** @description Levels to keep, one parameter each, e.g. `levels=warn&levels=error`. Omitted keeps every level; `limit` counts only kept records. */
                levels?: components["schemas"]["LogLevel"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retained framework logs, oldest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogRecord"][];
                };
            };
        };
    };
    streamLogs: {
        parameters: {
            query?: {
                /** @description Restrict to one flow's records, by flow identity. */
                flow?: string;
                /** @description Levels to keep, one parameter each, e.g. `levels=warn&levels=error`. Omitted keeps every level. */
                levels?: components["schemas"]["LogLevel"][];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Long-lived event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    getClusterStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pods as seen from the serving pod. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterStatus"];
                };
            };
        };
    };
    regenerateClusterToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The token was replaced. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cluster mode is off. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description The token could not be written to the cache. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build version derived from `CARGO_PKG_VERSION`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    getConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redacted application configuration as YAML. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigInfo"];
                };
            };
        };
    };
    agentsChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OpenAI-compatible completion, streamed when `stream` is true. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The AI gateway could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No AI gateway is configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    agentsModels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAI-compatible model list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description The AI gateway could not be reached. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No AI gateway is configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listConversations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conversation summaries, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conversations: components["schemas"]["ConversationSummary"][];
                    };
                };
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Conversation"];
                };
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No conversation with that id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    putConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpsert"];
            };
        };
        responses: {
            /** @description The conversation was stored. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Client-supplied conversation id (`[A-Za-z0-9_-]+`). */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The conversation is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation id is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The conversation store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    validateWorkspaceFiles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceFiles"];
            };
        };
        responses: {
            /** @description Issues per file; an empty list means every file is valid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceValidation"];
                };
            };
        };
    };
    listChanges: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Change summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        changes: components["schemas"]["ChangeSummary"][];
                    };
                };
            };
            /** @description `web.authoring` is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    proposeChange: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeProposal"];
            };
        };
        responses: {
            /** @description The recorded change. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description A file path is outside `flows/` and `resources/`. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `web.authoring` is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description No change with that id, or `web.authoring` is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    approveChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The change after publishing, `published` or `failed`. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description The request does not carry a user session. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No change with that id, or `web.authoring` is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change cannot be published in its status, or has invalid files. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rejectChange: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The rejected change. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Change"];
                };
            };
            /** @description The request does not carry a user session. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No change with that id, or `web.authoring` is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change is not pending or failed. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The change store is unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the identity provider. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
                error?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Login succeeded; redirects back into the web UI. */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing/invalid code or state, or the provider reported an error. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Code exchange or ID token validation failed. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out; continue to the provider or the web UI. */
            303: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserContext"];
                };
            };
            /** @description Not signed in. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description OIDC login is not configured. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    livez: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Not ready — no flows registered yet. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
