{{- $worker := index .Values "flowgen" -}}
{{- if and (or (not $worker.flowResources.existingConfigMaps) (eq (len $worker.flowResources.existingConfigMaps) 0)) $worker.flowResources.inline }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flowgen.fullname" . }}-resources
  labels:
    {{- include "flowgen.labels" . | nindent 4 }}
data:
{{- range $filename, $content := $worker.flowResources.inline }}
  {{ $filename }}: |
{{ $content | indent 4 }}
{{- end }}
{{- end }}
