{{- $worker := index .Values "flowgen" -}}
{{- if $worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgen.fullname" . }}-http-server
  labels:
    {{- include "flowgen.labels" . | nindent 4 }}
spec:
  type: {{ $worker.http_server.type }}
  selector:
    {{- include "flowgen.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ $worker.http_server.port }}
    targetPort: http
    protocol: TCP
    name: http
{{- if $worker.mcp_server }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgen.fullname" . }}-mcp-server
  labels:
    {{- include "flowgen.labels" . | nindent 4 }}
spec:
  type: {{ $worker.mcp_server.type }}
  selector:
    {{- include "flowgen.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ $worker.mcp_server.port }}
    targetPort: mcp
    protocol: TCP
    name: mcp
{{- end }}
{{- if $worker.ai_gateway }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flowgen.fullname" . }}-ai-gateway
  labels:
    {{- include "flowgen.labels" . | nindent 4 }}
spec:
  type: {{ $worker.ai_gateway.type }}
  selector:
    {{- include "flowgen.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ $worker.ai_gateway.port }}
    targetPort: ai-gateway
    protocol: TCP
    name: ai-gateway
{{- end }}
{{- end }}
